---
default_install_hook_types:
  - pre-commit
  - commit-msg

exclude: /(^LICENSE|^parsers\/src\/m49\/2025-09-05\.csv)/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: parsers/src/m49/2025-09-05.csv
      - id: fix-byte-order-marker
        exclude: parsers/src/m49/2025-09-05.csv
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        language_version: lts
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.7.0
    hooks:
      - id: action-validator
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.18.4
    hooks:
      - id: cargo-deny
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy
        args: ['--workspace', '--no-deps']
      - id: test
        args: ['--workspace']
