[package]
authors.workspace = true
categories = ["finance", "localization", "no-std", "no-std::no-alloc"]
description = "Static ISO3166 Data"
edition.workspace = true
keywords = ["iso3166", "m49"]
license.workspace = true
name = "iso3166-static"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
iso3166-macros.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
yare = "3"

[features]
alloc = ["serde?/alloc"]
default = ["alloc", "serde"]
serde = ["dep:serde"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
